<?php
require_once '../db.php';
checkLogin();
checkRole(['admin']);
?>

<!DOCTYPE html>
<html>
<head>
    <title>Admin - Latest Bills</title>
    <link rel="stylesheet" type="text/css" href="../style.css">
</head>
<body>
    <div class="header">
        <h2>Admin Dashboard - Latest Bills</h2>
        <div class="user-info">
            Welcome, <?php echo $_SESSION['username']; ?> | 
            <a href="../logout.php">Logout</a>
        </div>
    </div>
    
    <div class="menu">
        <a href="bills.php" class="active">Latest Bills</a>
        <a href="services.php">All Services</a>
        <a href="user_requests.php">Consumer Requests</a>
        <a href="employee_requests.php">Employee Requests</a>
    </div>
    
    <div class="container">
        <h3>Latest Electricity Bills</h3>
        
        <?php
        $sql = "SELECT b.*, c.name, c.service_number, u.username as generated_by_name 
                FROM bills b 
                JOIN consumers c ON b.consumer_id = c.id 
                JOIN users u ON b.generated_by = u.id 
                ORDER BY b.created_at DESC 
                LIMIT 50";
        $result = mysqli_query($conn, $sql);
        
        if (mysqli_num_rows($result) > 0) {
            echo '<table class="data-table">';
            echo '<tr>
                    <th>Bill ID</th>
                    <th>Service No</th>
                    <th>Consumer Name</th>
                    <th>Units</th>
                    <th>Amount</th>
                    <th>Due Date</th>
                    <th>Status</th>
                    <th>Generated By</th>
                    <th>Bill Date</th>
                    <th>Action</th>
                  </tr>';
            
            while ($row = mysqli_fetch_assoc($result)) {
                $status = $row['status'];
                if ($status != 'paid' && date('Y-m-d') > $row['due_date']) {
                    $status = 'Overdue';
                }
                
                $status_class = $status == 'paid' ? 'success' : ($status == 'Overdue' ? 'error' : '');
                
                echo '<tr>';
                echo '<td>' . $row['id'] . '</td>';
                echo '<td>' . $row['service_number'] . '</td>';
                echo '<td>' . $row['name'] . '</td>';
                echo '<td>' . $row['units'] . '</td>';
                echo '<td>₹' . $row['total_amount'] . '</td>';
                echo '<td>' . $row['due_date'] . '</td>';
                echo '<td><span class="' . $status_class . '">' . $status . '</span></td>';
                echo '<td>' . $row['generated_by_name'] . '</td>';
                echo '<td>' . $row['bill_date'] . '</td>';
                echo '<td><a href="../view_bill.php?id=' . $row['id'] . '" target="_blank" class="btn-small">View</a></td>';
                echo '</tr>';
            }
            echo '</table>';
        } else {
            echo '<p>No bills generated yet.</p>';
        }
        ?>
    </div>
</body>
</html>
